import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type ThemedValue = { light: string; dark: string };
type NamedToken<T> = { name: string; value: T; usage?: string };

type Tokens = {
  color: { tokens: NamedToken<ThemedValue>[] };
  spacing: { tokens: NamedToken<string>[] };
  radius: { tokens: NamedToken<string>[] };
  shadow: { tokens: NamedToken<ThemedValue>[] };
};

const root = join(import.meta.dirname, "..");
const tokens: Tokens = JSON.parse(
  readFileSync(join(root, "design/tokens.json"), "utf8"),
);

const compact = (value: string) => value.replace(/,\s+/g, ",").replace(/\s+/g, " ").trim();

const themed = (scheme: "light" | "dark") =>
  [...tokens.color.tokens, ...tokens.shadow.tokens]
    .map((token) => `  --${token.name}: ${compact(token.value[scheme])};`)
    .join("\n");

const scalar = [...tokens.spacing.tokens, ...tokens.radius.tokens]
  .map((token) => `  --${token.name}: ${token.value};`)
  .join("\n");

const extra = [
  "  --photo-glow: rgba(35,22,15,.22);",
  "  --content-max: 1152px;",
].join("\n");

const extraDark = "  --photo-glow: rgba(255,196,160,.35);";

const css = `/* Generated by scripts/tokens-to-css.ts from design/tokens.json. Do not edit. */

:root,
[data-theme="light"] {
${themed("light")}
${extra}
}

[data-theme="dark"] {
${themed("dark")}
${extraDark}
}

:root {
${scalar}
}
`;

writeFileSync(join(root, "app/tokens.css"), css);
console.log("app/tokens.css written");
